### ISSUE TITLE
skeletos and skeltos-react have a conflict in typings definition

### ISSUE THREAD

**Issue by sshaw69** [pythian/skeletos#24]
Have a project with dependencies to "skeletos" that was added with "yarn add skeletos".  Everything compiles clean.

When I introduce a dependency to skeletos-react that has dependencies to skeletos - I inevitably receive an error such as the following:

Error:(46, 44) TS2344: Type 'SkeletosStateType' does not satisfy the constraint 'AbstractSkeletosState'.
  Type 'AbstractSkeletosState' is not assignable to type 'AbstractSkeletosState'. Two different types with this name exist, but they are unrelated.
    Types have separate declarations of a private property '_cursor'.

There seems to be a problem in that there is a type definition to AbstractSkeletosState in both skeletos and skeletos-react that is causing a conflict

**Comment by sshaw69** [comment]
Perhaps I shouldn't be adding both skeletos and skeletos-react as package.json dependencies?  I only need skeletos-react ?

**Comment by sshaw69** [comment]
above comment appears to be the problem - I only need skeletos-react since it brings in skeletos indirectly

**Comment by atifsyedali** [comment]
Yea this sounds like a build (hammerpack) problem. I need to not include the d.ts files from core in the react package.

**Comment by atifsyedali** [comment]
Opened https://github.com/pythian/hammerpack/issues/34 in Hammerpack
