### ISSUE TITLE
SkeletosDB serialize / deserialize isn't symmetric / idempotent

### ISSUE THREAD

**Issue by sshaw69** [pythian/skeletos#25]
Run the following test - and you can get different output from input

import _ = require("lodash");
import {AbstractSkeletosState, SkeletosCursor, SkeletosTransaction} from "skeletos";

let stringsToTest: string[] = [
    "\\t\"DoubleQuotedName\"",
    "\\\t\n\b\f\r\t\u2028\u2029\"",
    "<Bracket Name>",
    "<script>alert(\"Break This\");</script>",
    "Bob",
    "///String///"
];

class TestDataState extends AbstractSkeletosState {

    /**
     * Test
     *
     */
    get testCursor(): SkeletosCursor {
        return this.cursor.select("test");
    }

    /**
     * Test
     *
     */
    get test(): string {
        return this.testCursor.get();
    }

    /**
     * Test
     *
     */
    set test(test: string) {
        this.testCursor.set(test);
    }
}

test("State Escape Tests", () => {
    const rootCursor: SkeletosCursor = new SkeletosCursor(false);
    const transaction: SkeletosTransaction = new SkeletosTransaction("State Escape Tests", rootCursor.db);

    _.forEach(stringsToTest, (testString: string) => {
        let userState: TestDataState = new TestDataState(rootCursor, transaction);
        userState.test = testString;

        const serializeState: string = rootCursor.db.serialize();

        const escapedState: string = _.escape(serializeState);

        expect(_.unescape(escapedState)).toBe(serializeState);

        rootCursor.db.deserialize(_.unescape(escapedState));

        userState = new TestDataState(rootCursor);

        expect(userState.test).toBe(testString);
    });
});

In a different implementation of the SkeletosDB - using URI encoding and decoding for the serialization methods allows the test to pass =>

    private escapeSpecialJsonCharacters(input: string): string {
        return encodeURIComponent(input);
    }

    private unescapeSpecialJsonCharacters(input: string): string {
        return decodeURIComponent(input);
    }

**Comment by atifsyedali** [comment]
Fixed. Reason why I changed it is because encodeURIComponent is really meant for URLs in the address bar...there's a lot of encoding overhead when writing the serialized form into the body of an HTML page.

**Comment by atifsyedali** [comment]
Btw I added that unit test in and published skeletos@2.0.6 package.
